Added error code verification when executing generate_test_files script.

diff --git a/test/bin2cpp_unittest/generate_test_files.sh.in b/test/bin2cpp_unittest/generate_test_files.sh.in
--- a/test/bin2cpp_unittest/generate_test_files.sh.in
+++ b/test/bin2cpp_unittest/generate_test_files.sh.in
@@ -1,3 +1,6 @@
+# Any commands which fail will cause the shell script to exit immediately
+set -e
+
 export TEST_NAME=testText10
 export OUTDIR=./generated_files/$TEST_NAME
 mkdir -p ${OUTDIR}
